#define ONE_WIRE_BUS_PIN 8

#define PIN_PIPE_SERVO_R 9
#define PIN_HEIGHT_SERVO_R 10
#define PIN_PIPE_SERVO_B 11
#define PIN_HEIGHT_SERVO_B 12

#define PIN_PIPE_POT_R A0
#define PIN_HEIGHT_POT_R A1
#define PIN_PIPE_POT_B A2
#define PIN_HEIGHT_POT_B A3

#define PIN_HEIGHT_SENSE_R 6
#define PIN_HEIGHT_SENSE_B 7

#define ONE_WIRE_BUS        13
