#define PIN_ONE_WIRE_BUS 13

#define PIN_PIPE_SERVO_R 5
#define PIN_HEIGHT_SERVO_R 4
#define PIN_PIPE_SERVO_B 3
#define PIN_HEIGHT_SERVO_B 2

#define PIN_PIPE_POT_R A3
#define PIN_HEIGHT_POT_R A0
#define PIN_PIPE_POT_B A1
#define PIN_HEIGHT_POT_B A2

#define PIN_SHOESENSE_R A4
#define PIN_SHOESENSE_B A5

#define PIN_DOWNBUTTON_R 12
#define PIN_DOWNBUTTON_B 11

#define PIN_MOTORSOFF_R 10
#define PIN_MOTORSON_R 9
#define PIN_MOTORSOFF_B 7
#define PIN_MOTORSON_B 8
